language: ruby
rvm:
- 2.2.0
- 2.3.1
- 2.5.0
- 2.6.1
script:
- bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: s7JXwHn+i4yWBshlBfkAa6H0ePUsXOZa40r0yiFvziGqh5RGtqT4MlGcYp/en8vSlBq1cHqxk1rkqBhN6uUlaKRTfLTRmOqBX/bLVzTwO8uRO6MgU3JkGxkL1YAFmQs6w/q5ZnYVhI35LN0dEi0vk2eDJayFvo1zw4nBJYWqAKqAw0uzoiCarEjqfknh8ZmMDr0KstJ1pDBVTsrUiQ/K0mfBCRK2Ho5qxk4uDed0UKSvmghhIg644K5SEHSA9tj1gelQTKxROCQB4kOXKl2y9+klUfDXAd27pzCYzt3Jt8ggZxDCZmFIun0YZzFoiEkDeHW0l9sxhntKncxQxyR0m2s6H8jE3fJBFJhg3/NAa9NBmED0evCrn2u1gqWM6rsDqlvLV3mA2Kh1irZsrGx78c1A54QAgPVZbN5CCKDymZibtkrGANyLPHOF/1oLl08Y3Y80UW+859yiR0qeixe6cJ6GsEg0e0Nhe6qeUcMGAstItzY6SzHCQCjL+bknnYILvupnvZQHyFUmY5lWYJDCD8k4+hg00LyAILrk6uIAx/TdH270s6Ep0liXtE6uCoGtcqjrCl9ENOsK9W5xSSe6c8CjBUhhnwO5fYdMtNYR7G44QwGb5FvisD+6jR8xxjUYdQsVOfjTq01jFz+Lgr/XZIn3mLbd8HSzq6jLiUt2zmY=
  gem: have-i-been-pwned
  on:
    tags: true
    repo: Dales-Lab/haveibeenpwned-ruby-sdk
notification:
  slack:
    rooms:
      secure: YtIdbbN6Fflga3zJI9mN6OLmz6+8fxcJuvHlQO77NIea2CvBUP9jvJ5b2nc2aBxw8MJjJtVwvc0p5DlnA2w3tMSrk5KTJuoGNQa83LgzZEBNZOrvwSTwXoHRVWP+KoSnMwdhzknzZqC7dbskku/1MAfVnEvgpJxdrjeGF4z6/lDMb2GPHhRyYOaIiTLM8Ig/j8TeGAB5Javt4MbrQOgmhl76lNzNb6BhHUgVice4HNAEJKnYB+aKElGdVC1L+gy1Qqf7bGBpciz0omODo0UXxADV+KA2NzApFctEiElarvb2MN+K9PAu70ouz5q9GQ97KbGuVQzzpNJ2R5WHxrYTj4tRsAkhjHeUnv1Otues6Uhnc6jYLGZZHtQs5qyC3sFJz2bVMqJd0VIUl9BLnBPhRaZ2pOHYHJoLpVgNUX2WurEDew46MwnvojBnxOQ1A4/PLttH/n8ApYSQVM2Ynrgr7ZRdPCm14YfCrG6jDZylL6RqX5NsJFUKLP5wl5q8siESDVgecyMBFcTSitKI+BF7asIAth4Mw/Q3IUEPT8LwcQqVvvzssYbMUsJayhOC5aNXBQbadJeFRDZBdMeL1buNuZnITtBQTOdkkTxnf2DbK3eb5rBz9MDaUICm01QArADbANDrIl8qugnKta7o7xgn3yxa8FghmoklC9z+QCyYHSM=
env:
  matrix:
    secure: N8raPga/MVy7t/QTxGpgYCqS8DzeDZxIkVa2jovcaHDc0Ul3v1oPnmlMbeE5dOHi2K9iiLnIH3Pe+u62Km4Vxp4xx7zS7Vm6yeMQyswUSkBGnMU75h3kaXGoaCIXR9b8yuJZajmME3fm5QH/rXBIOFQOCYEqLRpQzJgrGnHdgUGXm+QRL/anfFLcQGlH44Oyv1R4dAs0SFWZRcap3bnZLp04sSmvV5vG3pmca1YqSmMnUpptwP3UxIyTofwGbcDBHr86wxnaeUQYY/6ql52Di/yGhaswszJiKlQbI59beLhO/CGWQBrvjKyQR6Zk7YpX1pzfksQy/JWL8GW4ayB3qqifohRNChLH0/vD/EX219Cd02YXAXVVCAFvcAxRMab1Fct7rv/QHhzMfpsR6xazcFS+w6GBGcx1HtUvnPQXvt6kZ7oaQ1bTJ+5s02pz3BAJe5NoAYvxls12ou/ca6/B8pmCNDwwLzzO1XeiztKt0xE8tPpCYROeI4nel99i4nnYMMpoSUWqjwR4YKmoqkXlvMcKSCznHV7PhfXLF3h8vlK6dJWxJAo7iYcjcT2gRVt7biRt0K61zBRa/HF1zVSSfF/xpDkhSfV3nqu+UFlm9YIOri+2YSpvH4Az7sJPq8M2gaCasQUSevNEQ9BII/ouVvZK77vzUM+8LHo/X43fi0s=
